### PR TITLE
Use url-parse module instead of relying on native behavior that differs between environments

### PR DESCRIPTION
**Pull request by Robert-Frampton**
Replaces native use of the `URL` constructor and parsing urls with anchor tags with a combination of the [url-parse](https://www.npmjs.com/package/url-parse) package and [resolve-pathname](https://www.npmjs.com/package/resolve-pathname) package.

It also removes the node.js entry point so that server side use should function exactly the same as client side use.

In regards to the need for something like the `resolve-pathname` dependency, it's to ensure [this behavior](https://github.com/metal/metal-uri/blob/master/test/Uri.js#L215-L220) in particular doesn't break.

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
If we're comfortable with this change, I'd like to remove the ability to set a [custom parser](https://github.com/metal/metal-uri/blob/master/src/Uri.js#L180). Now that we don't need the different parser for Node.js it doesn't seem that useful of a feature. Thoughts?

**Comment by ipeychev** [comment]
Hey Rob, I also thought about that.
In general it is tempting to allow developer to change the parsing function. This might be useful in case of emergency - if for some reason our current one doesn't work, he will be able to replace it with something else. However, the probability for that to happen is very low:
1. If the developer wants to overwrite the parsing function without forking `metal-uri` he will have to keep the new implementation in his project and pass it via `setParseFn`. I don't think he will be happy to do this.
2. If he forks the module, then he would rather overwrite the content of parsing function, instead to create a new implementation and pass it via `setParseFn`.

Keeping that in mind, I would vote for removing it and releasing v3.0.0.

**Comment by jbalsas** [comment]
Hey @ipeychev, @eduardolundgren, I'm going to be merging this to the `develop` branch in preparation for a `3.0.0` release. That way we know for sure that this changes won't affect people in the `2.x` branch that might be forced to update their builds.

@Robert-Frampton, can you take care of removing the `setParseFn` feature and sending a followup PR?

@vbence86, final double-check here before I merge, please? :)

**Comment by vbence86** [comment]
LGTM. Nice piece of work.

**Comment by Robert-Frampton** [comment]
Hey @jbalsas, no problem 👍

**Comment by Robert-Frampton** [comment]
https://github.com/metal/metal-uri/pull/21

**Pull request merged**
